#!/usr/bin/env python3
"""NR-19 INVALIDATION CASCADE — approved-step changes propagate mechanically.

  invalidate_downstream.py --trig bnXXX --from-step 7 [--execute]

When an upstream step's approval changes (new decision, feedback applied),
everything downstream that was built on the old state must regenerate.
Without --execute: prints what WOULD be cleared (dry-run is the default —
this tool is destructive only to MARKERS and STAMPS, never to products;
products are regenerated by the driver, which skips nothing unmarked).
"""
import os, sys, re, json, argparse, glob, subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STEPS = ['0b','0','1','2','3','4','5','6','7','8','9']

# What each step's change invalidates, expressed as the driver's own phase
# markers (logs/campaign20/products/<trig>.<phase>) + the DONE marker + the
# approval stamps of later steps. Products are NEVER deleted here.
# Step numbers follow the OFFICIAL BurstWalkthrough ledger (PI ruling 2026-08-30:
# "The BurstWalkthrough ledger numbering is official: 0b = literature harvest,
# 0 = identity & GCN, 1 = data inventory, and so on."). Corrected 2026-08-31 —
# these notes previously used the old live_report numbering (its '3' said
# "source window"); the ACTIONS were and remain identical for steps 2-5.
CASCADE = {
  # any Stage-1 or binning change: everything spectral+temporal is stale
  '2': {'phases':'ALL','note':'detector set changed: re-bin then refit required; block reuse no longer applies to this burst'},
  # SHARPENED 2026-09-01 (PI: "Reinstate — blocks provably unchanged"): a background
  # change ALWAYS invalidates the fits, but it invalidates the BLOCKS only when the
  # REFERENCE NaI moved. scripts/27b builds the grid on the reference detector alone
  # (catalog-brightest if approved, else the approved NaI with most counts in its own
  # background gap) using THAT detector's own windows; the per-detector rows in the
  # block table are replicas, not independent computations. So a change to a
  # non-reference NaI, or to any BGO, requires REFIT ONLY — step 5 stays valid.
  '3': {'phases':'ALL','note':'background window(s) changed: refit required. RE-BIN (and step-5 demotion) ONLY if the REFERENCE NaI background moved — see the note above; a non-reference NaI or BGO change leaves the blocks valid'},
  '4': {'phases':'ALL','note':'source window changed: re-bin + refit required'},
  '5': {'phases':'ALL','note':'binning changed: refit required'},
  '6': {'phases':['t44b'],'note':'fits changed: promotion + SED grids + montages + param evolution + report must regenerate (driver reruns them; grids re-render per sweep_status)'},
  '7': {'phases':['t46','t44','t44b','t47','bala','t47b','t47c'],'note':'temporal changed: temporal suite + report must regenerate'},
  '8': {'phases':[],'note':'products changed: report must regenerate'},
  '9': {'phases':[],'note':'report step changed: report only'},
}
ALL_PHASES = ['t46','t44','t44b','t47','bala','t47b','t47c']

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--trig', required=True)
    ap.add_argument('--from-step', required=True, choices=STEPS)
    ap.add_argument('--execute', action='store_true')
    a = ap.parse_args()
    if not re.match(r'^bn[0-9]{9}$|^bnTEST[0-9]{3}$|^bnADJ[0-9]$', a.trig or ''):
        sys.stderr.write(f'ERROR: invalid trigger {a.trig!r}\n'); sys.exit(2)
    spec = CASCADE.get(a.from_step)
    if not spec:
        print(f'step {a.from_step}: nothing downstream to invalidate'); return
    phases = ALL_PHASES if spec['phases']=='ALL' else spec['phases']
    targets = [f'logs/campaign20/products/{a.trig}.{ph}' for ph in phases]
    targets.append(f'results/campaign20_products_done/{a.trig}')
    targets = [t for t in targets if os.path.exists(os.path.join(ROOT,t))]
    # later approval stamps become stale
    apf = os.path.join(ROOT,'results','sweep106',a.trig,'APPROVALS.json')
    stale = []
    st = json.load(open(apf)) if os.path.exists(apf) else {}
    for s in STEPS[STEPS.index(a.from_step)+1:]:
        if st.get(s,{}).get('status')=='APPROVED': stale.append(s)
    print(f'== NR-19 cascade for {a.trig}, upstream change at step {a.from_step} ==')
    print(f'   {spec["note"]}')
    for t in targets: print(f'   clear marker: {t}')
    for s in stale:   print(f'   demote approval: step {s} -> STALE (was APPROVED on old state)')
    if a.from_step == '3' and '5' in stale:
        print('   NOTE: step 5 (binning) was demoted. If ONLY a non-reference NaI or a BGO\n'
              '         background moved, the block grid is provably unaffected (27b builds it\n'
              '         on the reference NaI alone) — verify the block-table sha and reinstate\n'
              '         with that evidence rather than re-binning.')
    if not targets and not stale: print('   nothing to do (no markers, no later approvals)')
    if not a.execute:
        print('DRY RUN — add --execute to apply'); return
    for t in targets: os.remove(os.path.join(ROOT,t))
    for s in stale:
        st[s]['status']='STALE'; st[s]['stale_reason']=f'upstream step {a.from_step} changed'
    if stale: json.dump(st, open(apf,'w'), indent=1)
    print(f'APPLIED. Regenerate with: ./dev/campaign_products_driver.sh {a.trig}')
    subprocess.run([sys.executable, os.path.join(ROOT,'dev','live_report.py'),
                    '--trig', a.trig], check=False, cwd=ROOT)

if __name__=='__main__': main()
