#!/usr/bin/env python3
"""Splice the approved v3 fragments into a copy of the v2 manuscript (paper v3, decision 20 block gate).

    python3 dev/paper_v3_splice.py            # dry run: print the plan and the cross-reference check
    python3 dev/paper_v3_splice.py --write    # write paper_agentic/agentic_grb_v3.tex (v2 untouched)

What it does (architecture block, chng[1] of the v3 rewrite):
  * v2 lines 202-504 (section "The Agentic Workflow" through "The operating skeleton") are replaced by
        \\input{v3/sec3_harness}
        \\input{v3/sec4_lifecycle}
  * \\input{v3/sec7_objects} is inserted before v2's "Experimental Design" section (so the order is
    §3 harness, §4 lifecycle, §5 learning (v2 §4), §6 verification (v2 §5), §7 objects, §8 design, ...).
  * alias labels are added so that every cross-reference in the untouched v2 text still resolves:
    sec:doctrine -> the verification section, sec:casestudy -> the walkthrough-era results section.
  * the preamble gains the authority-table cell macro \\ac (the fragment's \\providecommand then no-ops).
  * an appendix section "Component roster" \\label{app:roster} inputs v3/tab_T1_roster (generated by
    dev/build_t1_roster.py) before the existing "Reproducibility" appendix.
Nothing is deleted from v2 without the decision sheet showing where it went
(paper_agentic/v3/DECISION_SHEET_architecture_block.md §3).
"""
import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
V2 = os.path.join(ROOT, 'paper_agentic', 'agentic_grb_v2.tex')
V3 = os.path.join(ROOT, 'paper_agentic', 'agentic_grb_v3.tex')
FRAGS = ['sec3_harness', 'sec4_lifecycle', 'sec7_objects']

# v2 line anchors (1-based, inclusive) — verified against the text, not trusted blindly: the script
# checks that the anchor lines carry the expected commands and stops otherwise.
BLOCK_FIRST = 202   # \section{The Agentic Workflow}
BLOCK_LAST = 504    # last line before \section{Learning Without Gradients}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--write', action='store_true')
    a = ap.parse_args()
    lines = open(V2, encoding='utf-8').read().split('\n')
    # --- anchor checks
    if '\\section{The Agentic Workflow}' not in lines[BLOCK_FIRST - 1]:
        sys.exit(f'anchor mismatch: line {BLOCK_FIRST} is not the Agentic Workflow section')
    if '\\section{Learning Without Gradients}' not in lines[BLOCK_LAST]:
        sys.exit(f'anchor mismatch: line {BLOCK_LAST + 1} is not the Learning section')
    for f in FRAGS + ['tab_T1_roster']:
        if not os.path.exists(os.path.join(ROOT, 'paper_agentic', 'v3', f + '.tex')):
            sys.exit(f'missing fragment v3/{f}.tex')

    head = lines[:BLOCK_FIRST - 1]
    tail = lines[BLOCK_LAST:]
    block = ['% ---- v3 architecture block (decision 20): §3 + §4 from fragments; v2 §3 (202-504) replaced; see',
             '% ---- paper_agentic/v3/DECISION_SHEET_architecture_block.md §3 for where every v2 paragraph went.',
             '\\input{v3/sec3_harness}', '', '\\input{v3/sec4_lifecycle}', '']
    out = head + block + tail
    text = '\n'.join(out)

    # --- §7 before Experimental Design
    m = re.search(r'^\\section\{Experimental Design[^\n]*$', text, flags=re.M)
    if not m:
        sys.exit('no Experimental Design section found')
    text = text[:m.start()] + '\\input{v3/sec7_objects}\n\n' + text[m.start():]

    # --- alias labels
    text = text.replace('\\section{Verification Doctrine} \\label{sec:verify}',
                        '\\section{Verification Doctrine} \\label{sec:verify}\\label{sec:doctrine}', 1)
    text = text.replace('\\section{Walkthrough-Era Results} \\label{sec:results}',
                        '\\section{Walkthrough-Era Results} \\label{sec:results}\\label{sec:casestudy}', 1)

    # --- preamble macro
    text = text.replace('\\newcommand{\\prov}{\\textsuperscript{(p)}}',
                        '\\newcommand{\\prov}{\\textsuperscript{(p)}}\n'
                        '\\newcommand{\\ac}[1]{\\parbox[t]{5.3cm}{\\raggedright #1}}   % authority-table cell (v3 §3)', 1)

    # --- appendix: component roster before Reproducibility
    m = re.search(r'^\\section\{Reproducibility\}[^\n]*$', text, flags=re.M)
    if not m:
        sys.exit('no Reproducibility appendix found')
    text = text[:m.start()] + ('\\section{Component roster} \\label{app:roster}\n'
                               'Table~\\ref{tab:roster} lists every component of the harness of \\S\\ref{sec:harness} '
                               'with its job in one sentence, its kind, how it executes, and its status at the census.\n'
                               '\\input{v3/tab_T1_roster}\n\n') + text[m.start():]

    # --- cross-reference check
    defs = set(re.findall(r'\\label\{([^}]+)\}', text))
    for f in FRAGS + ['tab_T1_roster']:
        defs |= set(re.findall(r'\\label\{([^}]+)\}', open(os.path.join(ROOT, 'paper_agentic', 'v3', f + '.tex'), encoding='utf-8').read()))
    refs = set(re.findall(r'\\(?:ref|eqref|pageref)\{([^}]+)\}', text))
    for f in FRAGS:
        refs |= set(re.findall(r'\\ref\{([^}]+)\}', open(os.path.join(ROOT, 'paper_agentic', 'v3', f + '.tex'), encoding='utf-8').read()))
    missing = sorted(refs - defs)
    print(f'v2 lines {BLOCK_FIRST}-{BLOCK_LAST} replaced ({BLOCK_LAST - BLOCK_FIRST + 1} lines); §7 inserted before Experimental Design; '
          f'appendix roster added; aliases sec:doctrine, sec:casestudy')
    print('unresolved cross-references after splice:', missing if missing else 'none')
    if a.write:
        open(V3, 'w', encoding='utf-8').write(text)
        print(f'wrote {os.path.relpath(V3, ROOT)} ({len(text.splitlines())} lines); v2 untouched')
    else:
        print('dry run — add --write to create agentic_grb_v3.tex')
    return 1 if missing else 0


if __name__ == '__main__':
    sys.exit(main())
