#!/usr/bin/env python
"""scripts/48_burst_report.py -- THE PER-BURST REPORT.

Vikas, 2026-08-13: "at the end of the whole analysis for a burst we should generate
a document that has all the figures with captions and also all the science done by
our agentic system on that -- basically if AI has to send a report of all of it."

Assembles one self-contained document per burst: every figure with a caption written
FROM THAT BURST'S NUMBERS (not a template sentence), the science at each step, the
literature comparison, and -- non-negotiable -- the honest flags: ties, L28
edge-constrained components, PANEL!=ENGINE stamps, missing products, P0 status.

LIGHT TIER (numpy/astropy only; no threeML, no refits -- it reads products).

  python scripts/48_burst_report.py --trig bn081125496 --out results/sweep106/bn081125496
  python scripts/48_burst_report.py --all            # every burst with products

Writes <out>/REPORT_<trig>.md. Markdown so it renders on GitHub with the figures
inline; convert with pandoc if a PDF is wanted.
"""
import os, re, glob, json, argparse, subprocess
import numpy as np
from astropy.table import Table

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SIMPLE = {"BAND", "CPL", "SBPL", "SBPLF"}
EDGE_LO, EDGE_HI, BBF = 20.0, 30.0, 3.9207


def _f(r, c):
    try:
        v = float(r[c]); return v if np.isfinite(v) else np.nan
    except Exception:
        return np.nan


def _jload(p):
    try:
        return json.load(open(p))
    except Exception:
        return {}


def _commit():
    try:
        return subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT,
                              capture_output=True, text=True).stdout.strip() or "unknown"
    except Exception:
        return "unknown"


def fig(rel, out, caption, L):
    """Embed a figure ONLY if it exists; otherwise say so (Shipping Gate)."""
    if os.path.exists(os.path.join(out, rel)):
        L += [f"![{rel}]({rel})", "", f"*{caption}*", ""]
    else:
        L += [f"> **figure missing:** `{rel}` — {caption}", ""]


def build(trig, out):
    L = []
    cat = Table.read(os.path.join(ROOT, "results", "background_intervals.ecsv"),
                     format="ascii.ecsv")
    rs = cat[[str(x).strip() == trig for x in cat["TRIGGER_NAME"]]]
    harvest = _jload(os.path.join(ROOT, "notes", "reconciliation", f"{trig}_harvest.json"))
    p0 = _jload(os.path.join(ROOT, "notes", "reconciliation", f"{trig}_P0_frozen.json"))
    grb = harvest.get("grb_name") or p0.get("grb_name") or ""
    ftab = os.path.join(out, trig, "spectral_fits.ecsv")
    t = Table.read(ftab, format="ascii.ecsv") if os.path.exists(ftab) else None

    # ---------------- header
    L += [f"# {trig}" + (f" — {grb}" if grb else ""), "",
          "**Analysis report — generated by the gated agentic pipeline.**", "",
          f"- repository commit: `{_commit()}`",
          f"- products: `{os.path.relpath(out, ROOT)}`",
          f"- P0 (frozen prediction) status: **{p0.get('P0_STATUS', 'none on file')}**",
          "- All numbers are PROVISIONAL until the campaign is frozen and signed off.", ""]

    # ---------------- 1 identity + literature
    L += ["## 1 · Identity and prior literature", ""]
    papers = harvest.get("papers") or []
    if papers:
        L += [f"{len(papers)} refereed paper(s) harvested for this burst "
              "(four-form ADS query plus the recovery channels).", "",
              "| bibcode | prompt-relevant content |", "|---|---|"]
        for p in papers[:12]:
            sec = str(p.get("prompt_sections") or p.get("key") or "").replace("|", "/")[:150]
            L.append(f"| `{p.get('bibcode','?')}` | {sec} |")
        L.append("")
    else:
        L += ["**No refereed literature found for this burst** — our fits are the first "
              "published time-resolved analysis. (A burst is only 'paperless' after the "
              "recovery channels have run: dotted trigger form, local-PDF grep, citation "
              "graph, Google Scholar.)", ""]
    if p0.get("predictions"):
        L += ["**Frozen predictions (P0)** — recorded before the fit table was opened:", ""]
        L += [f"- {str(x)}" for x in p0["predictions"]]
        L += ["", f"*Status `{p0.get('P0_STATUS','?')}`: only `BLIND_FROZEN` counts as a blind "
              "prediction; `ARCHIVAL_POSTFIT` rests on a previous production run (a disclosed "
              "prior); `NONBLIND_CONTAMINATED` saw this burst's own new values.*", ""]

    # ---------------- 2 data + detectors
    L += ["## 2 · Data inventory and detector selection", ""]
    if len(rs):
        L += ["| detector | angle (°) | background pre / post (s) | source (s) | approval |",
              "|---|---|---|---|---|"]
        for r in rs:
            L.append(f"| `{str(r['DETECTOR']).strip()}` | {_f(r,'DET_ANGLE'):.1f} | "
                     f"{_f(r,'BKG_NEG_START'):.1f}…{_f(r,'BKG_NEG_STOP'):.1f} / "
                     f"{_f(r,'BKG_POS_START'):.1f}…{_f(r,'BKG_POS_STOP'):.1f} | "
                     f"{_f(r,'SRC_START'):.2f}…{_f(r,'SRC_STOP'):.2f} | "
                     f"{str(r['APPROVAL_MODE']).strip()} |")
        L += ["", "Detector selection, background windows and the source interval are **human "
              "decisions adopted unchanged** by the pipeline, not re-derived. Individual "
              "detectors legitimately carry different background windows.", ""]
    fig(f"{trig}_step1_inventory.png", out,
        "Step 1–2. Left: each approved detector's response (DRM) coverage against the stamped "
        "source window — a bar must bracket the window for the effective area to be valid. "
        "Right: off-axis angles against the 60° selection rule.", L)

    # ---------------- 3 background + source
    L += ["## 3 · Background and source intervals", ""]
    fig(f"{trig}_step3_background.png", out,
        "Step 3. Per detector: the light curve (grey) with the fitted background polynomial "
        "(colour) through the approved pre/post windows (green); the source interval is red. "
        "The diagnostic question is whether the polynomial tracks the data inside the green "
        "windows AND extrapolates sanely beneath the burst.", L)
    fig(f"{trig}_step4_source.png", out,
        "Step 4. The source window (red) inside the common background gap (green). Where the "
        "source overruns the gap the figure says so — those are ledgered, accepted human "
        "overrides, not defects.", L)

    # ---------------- 4 binning
    L += ["## 4 · Time binning", ""]
    bf = os.path.join(out, "blocks", f"bb_blocks_spectral_{trig}.ecsv")
    if os.path.exists(bf):
        bt = Table.read(bf, format="ascii.ecsv")
        seen, rows = set(), []
        for r in bt:
            k = (round(_f(r, "T_START"), 3), round(_f(r, "T_STOP"), 3))
            if k in seen:
                continue
            seen.add(k); rows.append((k[0], k[1], _f(r, "SIGNIFICANCE")))
        sig = [r[2] for r in rows if np.isfinite(r[2])]
        L += [f"**{len(rows)} blocks** from Bayesian Blocks with a significance merge"
              + (f"; per-block significance {min(sig):.0f}–{max(sig):.0f}." if sig else "."),
              "", f"Narrowest {min(r[1]-r[0] for r in rows):.2f} s, widest "
              f"{max(r[1]-r[0] for r in rows):.2f} s — the binning adapts to the light curve "
              "rather than using a fixed cadence.", ""]
    fig(f"{trig}_step5_binning.png", out,
        "Step 5. Net light curve with the Bayesian blocks drawn as an adaptive step; the "
        "number on each block is its significance.", L)

    # ---------------- 5 spectroscopy
    L += ["## 5 · Time-resolved spectroscopy", ""]
    edge_notes, tie_notes = [], []
    if t is not None:
        pre = sorted({c[:-4] for c in t.colnames if c.endswith("_AIC")})
        L += ["Every block is fitted with the full model menu; the winner is the lowest AIC "
              "among **physically valid** fits, and evidence is reported as two margins "
              "(against the runner-up and against the best simple model).", "",
              "| block | interval (s) | winner | ΔAIC vs best simple | Band α | Ep (keV) | β | thermal |",
              "|---|---|---|---|---|---|---|---|"]
        for r in t:
            k = int(r["BLOCK"]); lab = "T_INT" if k < 0 else str(k)
            va = {}
            for p in pre:
                try:
                    if bool(r[f"{p}_VALID"]) and np.isfinite(float(r[f"{p}_AIC"])):
                        va[p] = float(r[f"{p}_AIC"])
                except Exception:
                    pass
            s = [v for p, v in va.items() if p in SIMPLE]
            x = [v for p, v in va.items() if p not in SIMPLE]
            d = (min(s) - min(x)) if (s and x) else np.nan
            verdict = ("**DECISIVE**" if d >= 10 else "STRONG" if d >= 6 else f"{d:+.1f}") \
                if np.isfinite(d) else "—"
            if np.isfinite(d) and 4.0 <= d < 6.0:
                tie_notes.append(f"block {lab}: ΔAIC = {d:.2f} — below the STRONG bar; a tie, "
                                 "not a preference")
            th = ""
            for kt, lrt, vc, nm in (("BANDBB_KT", "LRT_BANDBB_BAND", "BANDBB_VALID", "Band+BB"),
                                    ("CPLBB_KT", "LRT_CPLBB_CPL", "CPLBB_VALID", "CPL+BB")):
                if (np.isfinite(_f(r, lrt)) and _f(r, lrt) >= 9.2 and _f(r, kt) > 1.0544
                        and bool(r.get(vc, False))):
                    kt_v = _f(r, kt); feat = BBF * kt_v
                    cls = ("EDGE_CONSTRAINED" if feat < EDGE_LO else
                           "EDGE_MARGINAL" if feat < EDGE_HI else "in-band")
                    th = f"{nm} kT={kt_v:.1f} ({cls})"
                    if feat < EDGE_HI:
                        edge_notes.append(f"block {lab}: kT = {kt_v:.2f} keV → νFν turnover "
                                          f"{feat:.1f} keV — **{cls}**")
                    break
            L.append(f"| {lab} | {_f(r,'T_START'):.2f}…{_f(r,'T_STOP'):.2f} | "
                     f"{str(r['BEST_AIC_MODEL'])} | {verdict} | {_f(r,'BAND_ALPHA'):+.2f} | "
                     f"{_f(r,'BAND_EP'):.1f} | {_f(r,'BAND_BETA'):+.2f} | {th or '—'} |")
        eps = [_f(r, "BAND_EP") for r in t if int(r["BLOCK"]) >= 0]
        eps = [e for e in eps if np.isfinite(e)]
        if len(eps) > 1:
            trend = "hard-to-soft" if eps[-1] < eps[0] else "soft-to-hard / tracking"
            L += ["", f"**Spectral evolution:** Ep runs {eps[0]:.0f} → {eps[-1]:.0f} keV "
                  f"across the burst ({trend}).", ""]
    else:
        L += ["> **No fit table.** The fit produced no rows — see the burst's fit log. This is "
              "reported, not hidden.", ""]
    fig(os.path.join(trig, "spectral_evolution.png"), out,
        "Step 6. Fitted parameter evolution across blocks. Discontinuities that no emission "
        "mechanism could produce are the signature of a collapsed fit, not of the source.", L)
    fig(os.path.join(trig, "ep_kt_correlation.png"), out,
        "Step 6. Peak energy against blackbody temperature where a thermal component is "
        "significant. Absent when no block carries one.", L)
    fig(f"{trig}_nuFnu_best_montage.png", out,
        "Step 8. νFν spectrum per block with the **engine's stored winning model** — the panel "
        "displays the stored fit, it does not re-decide. Any `[! PANEL!=ENGINE]` stamp means "
        "the drawn curve drifted from the table: trust the table.", L)
    ov = sorted(glob.glob(os.path.join(out, f"{trig}_nuFnu_bin*_allmodels_overlay.png")))
    if ov:
        L += [f"### All-model overlays ({len(ov)} time bins)", "",
              "Each panel overlays **every valid model** for one time bin with the engine's "
              "winner in bold black. Where several curves lie on top of one another, the "
              "winner's *identity* is undetermined even when its AIC is lowest — adequacy is "
              "not identity.", ""]
        for p in ov:
            b = re.search(r"bin(\d+)", os.path.basename(p))
            fig(os.path.basename(p), out,
                f"Bin {b.group(1) if b else '?'}: all valid models, engine winner marked.", L)
    if os.path.exists(os.path.join(out, f"{trig}_nuFnu_TINT_allmodels_overlay.png")):
        fig(f"{trig}_nuFnu_TINT_allmodels_overlay.png", out,
            "Time-integrated spectrum: all valid models, engine winner marked. This is the row "
            "most often compared against published values.", L)

    # ---------------- 6 temporal
    L += ["## 6 · Temporal properties", ""]
    tc = os.path.join(ROOT, "results", "temporal_catalog_all106.ecsv")
    if os.path.exists(tc):
        tt = Table.read(tc, format="ascii.ecsv")
        row = [r for r in tt if str(r["TRIGGER_NAME"]).strip() == trig]
        if row:
            r = row[0]
            L += [f"- **T90 = {_f(r,'T90'):.2f} ± {_f(r,'T90_ERR'):.2f} s** "
                  f"(reference detector `{str(r['REF_DET']).strip()}`)",
                  f"- T50 = {_f(r,'T50'):.2f} s",
                  f"- minimum variability timescale ≈ {_f(r,'MVT_S'):.3f} s",
                  f"- spectral lag = {_f(r,'LAG_S'):.3f} s "
                  "(positive = low-energy photons arrive later)", ""]
            if bool(r.get("T90_WINDOW_TRUNCATED", False)):
                L += ["> ⚠ **T90 is window-truncated** — t5/t95 land on the edge of the "
                      "approved source window, so the duration is a LOWER LIMIT and is not "
                      "comparable with a catalogue T90.", ""]
            L += ["*Uncertainties come from Poisson realizations of the raw counts minus the "
                  "fitted background, using the same estimator as the point value inside the "
                  "approved window (audited 2026-08-13). Background-model uncertainty is not "
                  "propagated.*", ""]
    fig(f"{trig}_step7_temporal.png", out,
        "Step 7. Cumulative net counts per energy band with t5/t95 marked. The duration "
        "shortening toward higher energy is the expected band dependence — measured here per "
        "burst rather than assumed from a population relation.", L)

    # ---------------- 7 QC
    L += ["## 7 · Quality control and honest flags", ""]
    fig(f"{trig}_step9_qc.png", out,
        "Step 9. Top: per-block evidence for extra structure against the DECISIVE (ΔAIC ≥ 10) "
        "and STRONG (≥ 6) lines, winner labelled. Bottom: 3.92·kT for significant blackbodies "
        "against the 20 / 30 keV edge boundaries.", L)
    flags = []
    if edge_notes:
        flags.append("**Edge-constrained components (L28).** A blackbody's νFν turnover sits at "
                     "3.92·kT, so a low kT places all the evidence in the least-calibrated "
                     "channels near the 8 keV threshold. These values are retained in the record "
                     "but excluded from population statistics until the L28 checks pass:\n"
                     + "\n".join(f"  - {x}" for x in edge_notes))
    if tie_notes:
        flags.append("**Near-threshold margins.** A margin just under the bar is a tie, and must "
                     "be phrased as one:\n" + "\n".join(f"  - {x}" for x in tie_notes))
    man = os.path.join(out, "PRODUCTS.md")
    if os.path.exists(man):
        ms = open(man).read()
        miss = [l for l in ms.splitlines() if l.startswith("- [ ] **MISSING**")]
        if miss:
            flags.append(f"**Missing products ({len(miss)}).** Listed in `PRODUCTS.md` with the "
                         "reason; an absent product is stated, never silently skipped.")
    if flags:
        L += [f"{i+1}. {x}" for i, x in enumerate(flags)] + [""]
    else:
        L += ["No edge-constrained components, no near-threshold margins, no missing products.", ""]

    # ---------------- 8 provenance
    L += ["## 8 · Provenance and standing caveats", "",
          "- Stage-1 selections are human decisions, adopted unchanged and stamped.",
          "- Fits are blind: the model menu and validity gates decide, never a published value.",
          "- Winners are AIC-selected among valid fits; **adequacy is not identity** — a winning "
          "model is not a claim that the source is that model.",
          "- The significant-blackbody rule currently counts the Band+BB and CPL+BB nested "
          "tests; other nested pairs are not yet included (open item), so thermal counts are "
          "**provisional**.",
          "- All numbers here are provisional until the campaign is frozen and signed off.", ""]
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--trig"); ap.add_argument("--out"); ap.add_argument("--all", action="store_true")
    a = ap.parse_args()
    jobs = []
    if a.all:
        for m in sorted(glob.glob(os.path.join(ROOT, "results", "*", "*", "PRODUCTS.md"))) + \
                 sorted(glob.glob(os.path.join(ROOT, "results", "*", "PRODUCTS.md"))):
            d = os.path.dirname(m)
            hits = [os.path.basename(p) for p in glob.glob(os.path.join(d, "bn*")) if os.path.isdir(p)]
            if hits:
                jobs.append((hits[0], d))
    else:
        jobs = [(a.trig, a.out)]
    for trig, out in jobs:
        try:
            p = os.path.join(out, f"REPORT_{trig}.md")
            open(p, "w").write(build(trig, out))
            print(f"WROTE {p}")
            # PDF alongside it. xelatex, NOT pdflatex: the report contains unicode
            # (Delta, nu, degree) that pdflatex refuses.
            pdf = p[:-3] + ".pdf"
            r = subprocess.run(["pandoc", os.path.basename(p), "-o", os.path.basename(pdf),
                                "--pdf-engine=xelatex", "-V", "geometry:margin=2cm",
                                "-V", "colorlinks=true",
                                "--metadata", f"title={trig} - analysis report"],
                               cwd=out, capture_output=True, text=True)
            print(f"  PDF: {'ok' if r.returncode == 0 else 'FAILED ' + r.stderr[-120:]}")
        except Exception as e:
            print(f"   [WARN] {trig}: {e}")


if __name__ == "__main__":
    main()
